### ISSUE TITLE
Storybook issue locally

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#1116]
- [X] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [X] I have tested the latest version

## Steps to reproduce

1. Clone the project
2. Install the deps
3. Execute `yarn storybook` or `npm run storybook`

## Current behavior

```sh
flowbite-react on  main [⇕$] is 📦 0.6.4 via ⬢ v20.8.0 took 18.5s 
➜ yarn storybook
yarn run v1.22.19
$ storybook dev -p 3001
@storybook/cli v7.0.26

info => Starting manager..
WARN No story files found for the specified pattern: src/**/*.mdx
WARN You (or an addon) are using the 'config' preset field. This has been replaced by 'previewAnnotations' and will be removed in 8.0
info Addon-docs: using MDX2
info => Using implicit CSS loaders
ERR! Error: Cannot find module 'next/dist/shared/lib/router-context'
ERR! Require stack:
ERR! - /Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/nextjs/dist/preset.js
ERR! - /Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/core-common/dist/index.js
ERR! - /Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/telemetry/dist/index.js
ERR! - /Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/cli/dist/generate.js
ERR! - /Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/cli/bin/index.js
ERR! - /Users/rluders/Projects/rluders/flowbite-react/node_modules/storybook/index.js
ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
ERR!     at Module._resolveFilename (/Users/rluders/Projects/rluders/flowbite-react/node_modules/esbuild-register/dist/node.js:4768:36)
ERR!     at Function.resolve (node:internal/modules/helpers:136:19)
ERR!     at scopedResolve (/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/nextjs/dist/preset.js:1:9800)
ERR!     at addScopedAlias (/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/nextjs/dist/preset.js:1:9619)
ERR!     at configureRouting (/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/nextjs/dist/preset.js:1:13770)
ERR!     at Object.webpackFinal (/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/nextjs/dist/preset.js:1:28863)
ERR!     at Object.webpack (/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/builder-webpack5/dist/presets/custom-webpack-preset.js:1:3214)
ERR!     at starter (/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/builder-webpack5/dist/index.js:1:4653)
ERR!     at Module.start (/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/builder-webpack5/dist/index.js:1:8508)
ERR!  Error: Cannot find module 'next/dist/shared/lib/router-context'
ERR! Require stack:
ERR! - /Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/nextjs/dist/preset.js
ERR! - /Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/core-common/dist/index.js
ERR! - /Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/telemetry/dist/index.js
ERR! - /Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/cli/dist/generate.js
ERR! - /Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/cli/bin/index.js
ERR! - /Users/rluders/Projects/rluders/flowbite-react/node_modules/storybook/index.js
ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
ERR!     at Module._resolveFilename (/Users/rluders/Projects/rluders/flowbite-react/node_modules/esbuild-register/dist/node.js:4768:36)
ERR!     at Function.resolve (node:internal/modules/helpers:136:19)
ERR!     at scopedResolve (/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/nextjs/dist/preset.js:1:9800)
ERR!     at addScopedAlias (/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/nextjs/dist/preset.js:1:9619)
ERR!     at configureRouting (/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/nextjs/dist/preset.js:1:13770)
ERR!     at Object.webpackFinal (/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/nextjs/dist/preset.js:1:28863)
ERR!     at Object.webpack (/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/builder-webpack5/dist/presets/custom-webpack-preset.js:1:3214)
ERR!     at starter (/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/builder-webpack5/dist/index.js:1:4653)
ERR!     at Module.start (/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/builder-webpack5/dist/index.js:1:8508) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/nextjs/dist/preset.js',
ERR!     '/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/core-common/dist/index.js',
ERR!     '/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/telemetry/dist/index.js',
ERR!     '/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/cli/dist/generate.js',
ERR!     '/Users/rluders/Projects/rluders/flowbite-react/node_modules/@storybook/cli/bin/index.js',
ERR!     '/Users/rluders/Projects/rluders/flowbite-react/node_modules/storybook/index.js'
ERR!   ]
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected behavior

The Storybook should work without problems locally.

## Context

Why does it run on Vercel? 🤔

**Comment by rluders** [comment]
Best to go with #1118
